config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'

  resources :movies
  resources :users
  
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

    def self.create_user! (params_hash)
          User.create!(user_id: params_hash[:user]["user_id"], email: params_hash[:user]["email"], session_token: SecureRandom.base64)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def set_current_user
    @current_user ||= session[:session_token] && User.find_by_session_token(session[:session_token])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_filter :set_current_user
  
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @movies = Movie.all
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    
    if((User.find_by user_id: params[:user]["user_id"]) ==nil)
      flash[:notice] = "Invalid user-id/email combination"
      redirect_to login_path
    else
      @user=User.find_by user_id: params[:user]["user_id"]
      if(@user.email != params[:user]["email"])
        flash[:notice] = "Invalid user-id/email combination"
        redirect_to login_path
      else
        session[:session_token]=@user.session_token
        flash[:notice] = "You are logged in as #{@user.user_id}"
        redirect_to movies_path
      end
    end
  end
  
  def destroy
    flash[:notice] = "Successful Logout"
    session[:session_token]=nil
    set_current_user
    redirect_to movies_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end

  def create
    
        if((User.find_by user_id: params[:user]["user_id"]) !=nil)
          flash[:notice] = "Sorry, this user-id is taken. Try again."
          redirect_to new_user_path
        else
          User.create_user! (params)
          flash[:notice] = "Welcome #{params[:user]["user_id"]}. Your account has been created"
          redirect_to login_path
        end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  
  
  %body
    %h1.title Rotten Potatoes!
    
    #main
    
      -if !@current_user
        =button_to( "Sign Up/Login", login_path, :method => :get, :id => 'login')
        - if flash[:notice]
          #notice.flash_message= flash[:notice]
        - elsif flash[:warning]
          #warning.flash_message= flash[:warning]
  
        = yield
      -else
        #notice.flash_message="You are logged in as #{@current_user.user_id}"
        =button_to( "Logout", logout_path, :method => :delete, :id => 'logout' )
          
        =yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/users/new.html.haml
%h1 Sign-Up

= form_tag users_path do

  = label :user, :user_id, 'User-ID'
  = text_field :user, 'user_id', :id => 'signup_id'

  = label :user, :email, 'Email'
  = text_field :user, 'email', :id => 'signup_email'

  = submit_tag 'Create my account', :id => 'signup_submit'